person/urls.py
from django.urls import path
from person import views
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views

app_name='person'

urlpatterns = [ 
    path('login/', auth_views.LoginView.as_view(template_name='person/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='person:login'),name='logout'),
    path('',views.PersonListView.as_view(),name='list'),
    path('<int:pk>/',views.PersonDetailView.as_view(),name='detail'),
    path('note/create/',views.NoteCreate.as_view(),name='create-note'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

xfiles/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from person import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('person.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
            path('__debug__/',include(debug_toolbar.urls)),
            ]+ urlpatterns

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

person/models.py
from django_resized import ResizedImageField
from django.db import models
from django.urls import reverse

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=6,null=True,blank=True)

    def __str__(self):
        return f"{self.code} {self.name}"
    
class Person(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    nickname = models.CharField(max_length=30,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    image = ResizedImageField(size=[500,300],quality=85,keep_meta=True,upload_to='images/%Y/%m/%d/',default=None,null=True,blank=True)
   
    class Meta:
        ordering = ['surname','name']

    def __str__(self):
        return self.name +" "+self.surname

class Telephone(models.Model):
    number = models.CharField(max_length=10)
    person = models.ForeignKey(Person,on_delete=models.CASCADE, related_name='telephones')

    def __str__(self):
            return self.number

class Webpage(models.Model):
    url = models.URLField()
    person = models.ForeignKey(Person,null=True,blank=True,on_delete=models.CASCADE,related_name='websites')
    
    def __str__(self):
        return self.url

class Note(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    person = models.ForeignKey(Person, default=None,on_delete=models.CASCADE,null=True,blank=True,related_name='notes')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('person:detail', args=[str(self.person.id)])

class Place(models.Model):
    street = models.CharField(max_length=100)
    number = models.CharField(max_length=7)
    city = models.ForeignKey(City,on_delete=models.PROTECT,related_name='places')
    description = models.TextField(blank=True)
    persons = models.ManyToManyField(Person, default=None,blank=True,related_name='places')

    def __str__(self):
        owner = self.persons.all().first()
        if owner:
            return f"{self.city.name} {self.street} {self.number} - {owner.name} {owner.surname}"
        else:
            return f"{self.city.name} {self.street} {self.number}"

    

class Vehicle(models.Model):
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    fuel = models.CharField(max_length=3,blank=True)
    year = models.CharField(max_length=9,blank=True)
    plate = models.CharField(max_length=10)
    owner = models.ForeignKey(Person,default=None,on_delete=models.PROTECT,null=True,blank=True,related_name='vehicles')

    def __str__(self):
        return f"{self.brand} {self.model} {self.plate}"

class File(models.Model):
    file = models.FileField(upload_to='files/%Y/%m/%d/')
    person = models.ForeignKey(Person,on_delete=models.PROTECT,related_name='files')

    def __str__(self):
        return f"{self.file}"

person/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View,TemplateView,ListView,DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models
# Create your views here.

class PersonListView(ListView):
    model = models.Person
    paginate_by = 10

class PersonDetailView(LoginRequiredMixin,DetailView):
    model = models.Person
    template_name = 'person/person_detail.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        return context

class NoteCreate(LoginRequiredMixin,CreateView):
    model = models.Note
    fields = ['title','person','content']

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<ul class="nav navbar-nav">
					<li class="navbar-brand"><a href="{% url 'person:list' %}">X-Files</a></li>
					{% if user.is_authenticated %}
					<li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
					{% endif %}
					<li class="navbar-link"><a href="{% url 'person:list' %}">Ludzie</a></li>
					{% if user.is_authenticated %}
					<li class="navbar-link"><a href="{% url 'person:logout' %}">Wyloguj</a></li>
					{% else %}
					<li class="navbar-link"><a href="{% url 'person:login' %}">Zaloguj</a></li>
					{% endif %}
				</ul>
		</nav>

		<div class="container">
			{% block body_block %}
			Anything inside will be inherited
			{% endblock %}
		</div>
		{% block pagination %}
    {% if is_paginated %}
    <center>
    	<nav>
        <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
		<li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Poprzednia</a></li>
		<li class="page-item"><a class="page-link" href="{{ reqiuest.path }}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}
		<li class="page-item active"><a class="page-link" href="{{ reqiuest.path }}">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
		<li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
		<li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Następna</a></li>
                {% endif %}
        </ul>
        </nav>
    </center>
    {% endif %}
  {% endblock %}	
	</body>
</html>

templates/index.html
<h1>Index</h1>

templates/person/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<ul class="nav navbar-nav">
					<li class="navbar-brand"><a href="{% url 'person:list' %}">X-Files</a></li>
					<li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
					<li class="navbar-link"><a href="{% url 'person:list' %}">People</a></li>
				</ul>
		</nav>

		<div class="container">
			{% block body_block %}
			Anything inside will be inherited
			{% endblock %}
		</div>
	</body>
</html>

templates/person/index.html
<html><head><title>Lista Osob w Bazie</title>
	</head>
<body>
<h1>Lista osob w bazie</h1>
{% if people %}
{% for person in people %}
{{ person.name }} {{ person.surname }} <br>
{% endfor %}
{% else %}
	No people in the database
{% endif %}
</body>
</html>

templates/person/login.html
{% extends "base.html" %}

{% block body_block %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'person:login' %}">
{% csrf_token %}
<div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">{{ form.username.label_tag }}</label>
    <div class="col-sm-10">
      {{ form.username }}
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">{{ form.password.label_tag }}</label>
    <div class="col-sm-10">
	{{ form.password }}
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
	<input type="submit"  class="btn btn-primary" value="login">
	<input type="hidden" name="next" value="{{ next }}">
    </div>
  </div>
</form>

{# Assumes you set up the password_reset view in your URLconf #}
{#<p><a href="{% url 'password_reset' %}">Lost password?</a></p>#}

{% endblock %}

templates/person/note_form.html
{% extends "base.html" %}

{% block body_block %}
  <form action="" method="post">
    {% csrf_token %}

<div class="form-group row">
    <label for="input" class="col-sm-2 col-form-label">{{ form.title.label_tag }}</label>
    <div class="col-sm-10">
      {{ form.title }}
    </div>
  </div>
  <div class="form-group row">
    <label for="input" class="col-sm-2 col-form-label">{{ form.person.label_tag }}</label>
    <div class="col-sm-10">
        {{ form.person }}
    </div>
  </div>
  <div class="form-group row">
    <label for="input" class="col-sm-2 col-form-label">{{ form.content.label_tag }}</label>
    <div class="col-sm-10">
        {{ form.content }}
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
        <input type="submit"  class="btn btn-primary" value="Dodaj">
    </div>
  </div>

  </form>
{% endblock %}

templates/person/person_detail.html
<!DOCTYPE html>
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% extends 'base.html' %}
{% block body_block %}
<h1>Akta {{ person.name }} {{ person.surname }}</h1>

<div class="card" style="width: 18rem; float:left; margin-right:50px">
	{% if person.image %}
  		<img class="card-img-top" src="{{ person.image.url }}" alt="Profile image">
  	{% else %}
  		<img class="card-img-top" src="https://toppng.com/uploads/preview/erson-outline-icon-png-person-icon-png-white-11562864385wyirbbsupu.png" alt="Profile image">
	{% endif %}

  <div class="card-body">
    <h5 class="card-title">{{ person.name }} {{ person.surname }}</h5>
    <p class="card-text"> <i>{{ person.places.first.street }} {{ person.places.first.number }}</i></p>
    {% if request.user.is_authenticated %}	
    <p class="card-text">
	<a href="{% url 'admin:person_person_change' person.pk %}">Zmień</a>
    </p>
    <p class="card-text">
	<a href="{% url 'person:create-note' %}">Dodaj notatkę</a>
    </p>
    {% endif %}
  </div>
  <ul class="list-group list-group-flush">
    {% if person.nickname %}
    <li class="list-group-item">ksywka: {{ person.nickname }}</li>
    {% endif %}
    {% if person.email %}
    <li class="list-group-item">e-mail: {{ person.email }}</li>
    {% endif %}
    {% if person.telephone %}
    <li class="list-group-item">tel: {{ person.telephone }}</li>
    {% endif %}
  </ul>
  <div class="card-body">
	{% for website in person.websites.all %}
		<a href="{{ website }}" class="card-link">{{website}}</a>
	{% endfor %}
  </div>
{% if person.vehicles.all %}
<ul class="list-group list-group-flush">
<li class="list-group-item active">Pojazdy</li>
{% endif %}
{% for vehicle in person.vehicles.all %}
  <div class="card-body">
	  <li class="list-group-item">	{{ vehicle.brand }} {{ vehicle.model }}
		  <a href="https://tablica-rejestracyjna.pl/{{ vehicle.plate }}" target="_blank">{{vehicle.plate}}</a> </li>
  </div>
{% endfor %}
  </ul>
</div>

<div class="card-deck">
	{% for note in person.notes.all %}
	<div class="card" style="width:36rem;">
	  <div class="card-body">
	    <h5 class="card-title">{{ note.title }}</h5>
	    <h6 class="card-subtitle mb-2 text-muted">{{ note.created }}</h6>
	    <p class="card-text">{{ note.content |linebreaks }}</p>
	    {% if request.user.is_authenticated %}
	    <p class="card-text"><a href="{% url 'admin:person_note_change' note.pk %}">Zmień</a></p>
	    {% endif %}
	  </div>
	</div>
{% endfor %}
</div>
{% endblock %}

templates/person/person_list.html
<!DOCTYPE thml>
{% extends 'base.html' %}

{% block body_block %}
<h1>Kartoteka</h1>

{% for person in person_list %}

<div class="card" style="width: 18rem; float:left; margin:20px; heigth: 36 rem;">
	{% if person.image and request.user.is_authenticated %}
  		<img class="card-img-top" style="height: 182px; width: 182px;" src="{{ person.image.url }}" alt="Profile image">
  	{% else %}
  		<img class="card-img-top" style="height: 182px;width: 182px;" src="https://toppng.com/uploads/preview/erson-outline-icon-png-person-icon-png-white-11562864385wyirbbsupu.png" alt="Profile image">
	{% endif %}

  <div class="card-body">
	  {% if request.user.is_authenticated %}
	  	<h5 class="card-title">{{ person.name }} {{ person.surname }}</h5>
		<p class="card-text"> <i>{{ person.places.first.street }} {{ person.places.first.number }}</i></p>
    		<p><a class="card-link" href="{% url 'person:detail' pk=person.pk %}">Zobacz akta</a></p>
	  {% else %}
		  <h5 class="card-title">***** *****</h5>
		  <p class="card-text"> <i>******</i></p>
	  {% endif %}
  </div>
</div>
{% endfor %}
{% endblock %}